### ISSUE TITLE
[BUG] sqlite3.IntegrityError: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by lCyou** [kindai-ecl/discord-bot-commit-time#18]
**バグの詳細**

外部キー制約でなんかエラーが出てるらしい

**再現**

再現不能（）

**Botで何がしたかったか**

ボイスチャンネルで稼働時間を計測したい。
１ヶ月運用してきているけれど初めてボイスチャンネルでのStateエラーが出ている。どういう操作を行なったか見当がついていないが外部制約キーのRelationが設定できていない？

**スクリーンショット**

```
2024-07-09 14:01:22 2024-07-09 05:01:22 ERROR    discord.client Ignoring exception in on_voice_state_update
2024-07-09 14:01:22 Traceback (most recent call last):
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
2024-07-09 14:01:22     self.dialect.do_execute(
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
2024-07-09 14:01:22     cursor.execute(statement, parameters)
2024-07-09 14:01:22 sqlite3.IntegrityError: FOREIGN KEY constraint failed
2024-07-09 14:01:22 
2024-07-09 14:01:22 The above exception was the direct cause of the following exception:
2024-07-09 14:01:22 
2024-07-09 14:01:22 Traceback (most recent call last):
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/discord/client.py", line 441, in _run_event
2024-07-09 14:01:22     await coro(*args, **kwargs)
2024-07-09 14:01:22   File "/app/bot/bot.py", line 41, in on_voice_state_update
2024-07-09 14:01:22     timelogger.stamp_time_log(member.id, now, 'start')
2024-07-09 14:01:22   File "/app/bot/timelogger.py", line 48, in stamp_time_log
2024-07-09 14:01:22     session.commit()
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 597, in commit
2024-07-09 14:01:22     return self._proxied.commit()
2024-07-09 14:01:22            ^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
2024-07-09 14:01:22     trans.commit(_to_root=True)
2024-07-09 14:01:22   File "<string>", line 2, in commit
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
2024-07-09 14:01:22     ret_value = fn(self, *arg, **kw)
2024-07-09 14:01:22                 ^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
2024-07-09 14:01:22     self._prepare_impl()
2024-07-09 14:01:22   File "<string>", line 2, in _prepare_impl
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
2024-07-09 14:01:22     ret_value = fn(self, *arg, **kw)
2024-07-09 14:01:22                 ^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
2024-07-09 14:01:22     self.session.flush()
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
2024-07-09 14:01:22     self._flush(objects)
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
2024-07-09 14:01:22     with util.safe_reraise():
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
2024-07-09 14:01:22     raise exc_value.with_traceback(exc_tb)
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
2024-07-09 14:01:22     flush_context.execute()
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
2024-07-09 14:01:22     rec.execute(self)
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
2024-07-09 14:01:22     util.preloaded.orm_persistence.save_obj(
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
2024-07-09 14:01:22     _emit_insert_statements(
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
2024-07-09 14:01:22     result = connection.execute(
2024-07-09 14:01:22              ^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
2024-07-09 14:01:22     return meth(
2024-07-09 14:01:22            ^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
2024-07-09 14:01:22     return connection._execute_clauseelement(
2024-07-09 14:01:22            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
2024-07-09 14:01:22     ret = self._execute_context(
2024-07-09 14:01:22           ^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1850, in _execute_context
2024-07-09 14:01:22     return self._exec_single_context(
2024-07-09 14:01:22            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1990, in _exec_single_context
2024-07-09 14:01:22     self._handle_dbapi_exception(
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
2024-07-09 14:01:22     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
2024-07-09 14:01:22     self.dialect.do_execute(
2024-07-09 14:01:22   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
2024-07-09 14:01:22     cursor.execute(statement, parameters)
2024-07-09 14:01:22 sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
2024-07-09 14:01:22 [SQL: INSERT INTO time_logs (user_id, timestamp, status) VALUES (?, ?, ?)]
2024-07-09 14:01:22 [parameters: (1226778257068920913, '2024-07-09 14:01:22.300326', 'start')]
2024-07-09 14:01:22 (Background on this error at: https://sqlalche.me/e/20/gkpj)
```
**動作環境**
 - OS X
 - デスクトップアプリ

**追加詳細t**

**Comment by lCyou** [comment]
hotfixが本番環境に入っていなかったので今回のエラーが起きたと考えられる。
対策としてDiscordのギルドメンバー全員を想定して
- Userのロールを監視する
- ボイスチャンネルのカテゴリーを分ける（他のインテントが必要になる）
- etc...
